modules: Add missing (void *) casts
Add intermediate cast to type void * when assigning the address of
struct fwk_event::params as a module specific struct pointer. This
is needed of prevents build warning for example when compiling
SCP-firmware as OP-TEE OS library, since ::params is a byte pointer
whereas target pointer is likely to have high alignment requiements
as illustrated by the following build warning trace when using GCC-9.2:

module/scmi_clock/src/mod_scmi_clock.c:629:14: error: cast increases required alignment of target type [-Werror=cast-align]
  629 |     params = (struct event_request_params *)event.params;

Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>